### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by hardbyte** [NICTA/javallier#17]
JavaDoc should be put somewhere publicly available like [python-paillier on readthedocs](https://python-paillier.readthedocs.org/en/stable/index.html)

**Comment by hardbyte** [comment]
https://www.javadoc.io/ looks like a good candidate

**Comment by mpnd** [comment]
JavaDoc for all versions of Javallier is available in [https://www.javadoc.io/](https://www.javadoc.io/). 

Documentation for the latest version: [https://www.javadoc.io/doc/com.n1analytics/javallier_2.10/0.5.0](https://www.javadoc.io/doc/com.n1analytics/javallier_2.10/0.5.0).
