### ISSUE TITLE
Command line binary

### ISSUE THREAD

**Issue by hardbyte** [NICTA/javallier#23]
To aide testing integration between python-paillier and javallier, add a command line program to:
- generate and serialize key pairs (of different key sizes)
- encrypt and serialize given a public key and a plaintext number
- decrypt given a private key and the ciphertext
- add two encrypted numbers together
- add an encrypted number to a plaintext number
- multiply an encrypted number to a plaintext number

Initially use a standard encoding scheme.

Associated issue on [python-paillier#6](https://github.com/NICTA/python-paillier/issues/6).

**Comment by hardbyte** [comment]
Apache commons provides a useful library to help: https://commons.apache.org/proper/commons-cli/usage.html

**Comment by mpnd** [comment]
CLI has been included in master branch as of dcdb3c85768994cb87efd81dcb264e29a6362124.

I notice the following issues:
- It cannot encrypt negative number (Issue #34). The main problem is it can't properly read negative number from the command line, even after following the note in the help menu.
- Some options are inconsistent (Issue #35). Using `-v` and `--verbose` gives different results. Likewise for `-h` and `--help`.
- It currently only supports one type of Paillier Context (Issue #36). Ideally users should be able to provide a specific Paillier Context set up.
