### ISSUE TITLE
Why are you using base 2 for the number encoding ?

### ISSUE THREAD

**Issue by malzantot** [NICTA/javallier#4]
I wonder why you have chosen to use base 2 for the floating number encoding.
This would make compatibility issues when passing communicating with software using the your python-paillier library which uses base 16 by default.
Also, as the higher base value, the less information is leaked by the exponent, I wonder what made you decide to use base 2 ?

Thanks,
Moustafa

**Comment by hardbyte** [comment]
The base in python-paillier should be configurable but ideally both javallier and python-paillier will use the same default base.

As for the information leakage, as mentioned in the [python-pallier docs](https://python-paillier.readthedocs.org/en/stable/caveats.html#information-leakage) if the exponent is chosen ahead of time this shouldn't be an issue.
