### ISSUE TITLE
Add methods to check the properties of a Number

### ISSUE THREAD

**Issue by mpnd** [NICTA/javallier#6]
Having some methods to check the properties of a `Number` could be useful. For example, `isValidLong()` to check whether a number can be converted to a valid long or `isFiniteDouble` to check whether a number can be converted to a finite double.

**Comment by wilko77** [comment]
If I understand correctly, you want some methods to test if a `Number` can be decoded exactly as a `Long` or `Double`. 
I don't like the suggested names: 
- `isValidLong()` implies that there are invalid `Long`. 
- `isFiniteDouble()` all `Double` representations of reals except infinity are finite. Same for `Number`.

How about: `decodesExactlyToLong()`, `decodesExactlyToDouble()`, ...

**Comment by mpnd** [comment]
`Number` class has been removed in 84b894a2a7eb447ffd6da967fa507b47ca9319b5.
